"""A short motivational quote for every day of the year, the same on every box that day.

Owner, 2026-10-01: *"Let's come up with a short motivational quote for every day of the year and it goes out to
everybody. That should be the headline."* Approved with the Morning Review scope ("Ok go", same day;
docs/SCOPE_MORNING_REVIEW_V2.md). Original lines written for Ownbox, so none needs an attribution and none can be
misquoted. Not a well-known saying reworded either (OSDev1's review of #1779 found five, and a second pass
found more: "Bloom where you're planted", "You can do hard things"). AND NO SEASONS: the same line goes to a
box in Sydney, where 1 March is autumn and 21 December is the longest day. Edited here, and nowhere else: tests/test_morning_review_v2.py holds every date to one quote, and short.
"""
from __future__ import annotations

from datetime import date

# {month: [day 1, day 2, ...]}. February has 29: a leap day gets its own.
QUOTES: dict[int, tuple[str, ...]] = {
    1: (
        "A fresh page. Write something you'll be proud of.",
        "Start small. Start today. Start anyway.",
        "Momentum is built one finished task at a time.",
        "The best plan is the one you begin.",
        "The people you admire started out unsure too.",
        "Show up today, and tomorrow gets easier.",
        "Clarity comes from action, not from waiting.",
        "Do one thing today your future self will thank you for.",
        "Progress beats perfect, every single time.",
        "Small steps still move you forward.",
        "Your business grows at the speed of your follow-through.",
        "Make today's work a gift to next month.",
        "Done is a beautiful word.",
        "Begin with the hardest thing; the rest gets lighter.",
        "Consistency turns ordinary days into great years.",
        "Every customer remembers how you made them feel.",
        "Ideas are free. Finishing is where the value is.",
        "A little better than yesterday is plenty.",
        "Courage is just one more try.",
        "Focus on what you can move today.",
        "The work you do quietly shows up loudly later.",
        "Good things are built by people who keep showing up.",
        "Today is a good day to finish something.",
        "Your next customer is looking for exactly you.",
        "Be the reason someone's day got easier.",
        "Keep promises to yourself first.",
        "Simple and done beats clever and waiting.",
        "Make it work, then make it wonderful.",
        "Growth starts at the edge of comfortable.",
        "You don't need more time. You need one clear next step.",
        "End the month knowing you showed up.",
    ),
    2: (
        "New month, same you, better habits.",
        "Kindness is a strategy that never goes out of style.",
        "Every reply is a chance to build trust.",
        "Slow progress is still progress.",
        "Your effort today is tomorrow's advantage.",
        "Great businesses are built on small, kept promises.",
        "Choose one priority and give it your best hour.",
        "People buy from people they believe in. Be believable.",
        "You've solved harder problems than today's.",
        "A good question opens more doors than a great pitch.",
        "Do your part today. Let tomorrow do its part.",
        "Listen first. The answer is usually in the question.",
        "Energy is contagious. Bring some today.",
        "Love what you build, and others will too.",
        "Halfway through the month is a great time to begin.",
        "A finished draft beats a perfect idea.",
        "Stay curious. It keeps the work fresh.",
        "Every no makes room for a better yes.",
        "Your story is worth telling well.",
        "Pick the next useful thing and do it well.",
        "Patience and persistence are a powerful pair.",
        "Generosity comes back around.",
        "One clear message beats ten clever ones.",
        "Rest is part of the work.",
        "Make your customer the hero of the story.",
        "Little wins add up to big seasons.",
        "Trust is earned in small moments.",
        "Finish strong. Start the next month lighter.",
        "A bonus day. Spend it on something that matters.",
    ),
    3: (
        "A new month. Plant something you'd like to see grow.",
        "Ambition looks a lot like showing up again.",
        "You're closer than you think.",
        "Make room for what's working.",
        "Every day is a chance to get a little better.",
        "A clear yes and a kind no both save time.",
        "The best marketing is a happy customer.",
        "Lift someone up today.",
        "Build things that last.",
        "Ask for what you want. You might just get it.",
        "Your attention is your most valuable tool.",
        "The right people are looking for you.",
        "Know your one priority today, and guard it.",
        "Curiosity turns problems into puzzles.",
        "The way ahead gets clearer once you're moving.",
        "Make it easy for people to say yes.",
        "Get ready today, and good breaks will know where to find you.",
        "Celebrate the small wins out loud.",
        "Do it well, then do it again.",
        "Fresh season, fresh start.",
        "Grow at your own pace. It's still growth.",
        "Good work speaks for itself, eventually.",
        "Simplify one thing today.",
        "Every message you send is a small handshake.",
        "Choose progress over pressure.",
        "Whatever you repeat gets easier. Repeat the good things.",
        "Be easy to work with. It's rarer than you think.",
        "Today's effort is next season's harvest.",
        "Look how far you've already come.",
        "Plans are good. Starts are better.",
        "Close the month with something finished.",
    ),
    4: (
        "A new month to build something wonderful.",
        "Your customers are rooting for you.",
        "Make one person's day today.",
        "Steady wins more often than sudden.",
        "Every step forward counts, even the tiny ones.",
        "Do less, but do it beautifully.",
        "Be proud of the work only you can do.",
        "Growth loves consistency.",
        "Show people what you're building.",
        "A helpful answer is the best advertisement.",
        "Make today simple. Make it count.",
        "You're building something that matters.",
        "The first step is always the bravest.",
        "Good habits are quiet superpowers.",
        "Halfway is a great place to pick up speed.",
        "Stay open. Opportunity knocks softly.",
        "Lead with generosity.",
        "Do the thing you've been putting off. It's smaller than it looks.",
        "Every season of work has its harvest.",
        "Trust the process you've built.",
        "Be the business you'd love to buy from.",
        "Keep your promises and your word gets stronger.",
        "Wherever you are today is a fine place to grow.",
        "Make your work a little more delightful.",
        "Today's focus is tomorrow's freedom.",
        "You've handled tough days before. Today is no different.",
        "Say thank you. It goes a long way.",
        "Waiting has never finished anything. Begin.",
        "Make room for what lights you up.",
        "End the month with gratitude.",
    ),
    5: (
        "A bright new month. Make it yours.",
        "Big results come from small, daily care.",
        "Be patient with your growth.",
        "One good conversation can change a whole week.",
        "Choose excellence in the small things.",
        "Be the steady one.",
        "Your work makes a difference to someone.",
        "Every finished task is a win. Count them.",
        "Build relationships, not just transactions.",
        "The sun comes up every day. So can you.",
        "Give your best to the hour you're in.",
        "Nervous and doing it anyway is still doing it.",
        "Make the next step obvious.",
        "Joy is a fine reason to work hard.",
        "Midway through the month, still going strong.",
        "A warm welcome turns visitors into regulars.",
        "Today, aim for better, not perfect.",
        "Strong foundations make room for big growth.",
        "Curiosity keeps a business young.",
        "Every expert keeps learning.",
        "Keep your eyes on the horizon and your hands on the work.",
        "Make it personal. People notice.",
        "Little improvements compound.",
        "Trust yourself. You've earned it.",
        "Good energy is good business.",
        "Take the next small step with confidence.",
        "Do the work you'd be proud to show.",
        "A clear head makes good decisions.",
        "Celebrate how far you've come this month.",
        "Find the fun in the work.",
        "Finish May with something you love.",
    ),
    6: (
        "A new month. Take the first bright step.",
        "Make today light and productive.",
        "Your future is built in ordinary moments.",
        "Be someone people are glad to hear from.",
        "Show up with your whole heart.",
        "A simple system beats a complicated wish.",
        "Every answer you give builds your reputation.",
        "Keep it simple. Keep it moving.",
        "You're allowed to grow slowly.",
        "Make one thing better than you found it.",
        "The best ideas arrive while you're working.",
        "Lead with kindness. Follow through with excellence.",
        "Make your customers feel seen.",
        "Today is a great day to be helpful.",
        "Halfway through the year. Look what you've built.",
        "Celebrate progress, not just the finish.",
        "Choose the brave option.",
        "Patience is a quiet kind of strength.",
        "Let your work be your welcome.",
        "Plenty of hours today. Give a few to what matters.",
        "Bright days are made, not found.",
        "Every relationship starts with a reply.",
        "Focus is the secret ingredient.",
        "Do what you said you'd do.",
        "Make it easy, make it kind, make it real.",
        "A good day's work is a quiet joy.",
        "Let today be a little lighter.",
        "Small wins, every day, all year.",
        "Keep the promise you made to yourself.",
        "Close the half-year proud.",
    ),
    7: (
        "A brand-new half. Begin it boldly.",
        "Your best work is still ahead.",
        "Make room for rest, and the work gets better.",
        "Freedom is built on good habits.",
        "Be generous with your knowledge.",
        "Every day is a chance to earn trust.",
        "Make the complicated simple.",
        "Show up, speak up, follow up.",
        "A good name is built one interaction at a time.",
        "Let your enthusiasm show.",
        "Choose growth over comfort today.",
        "One focused hour can change the week.",
        "Be the calm in someone's busy day.",
        "Good work is never wasted.",
        "Halfway through July. Bring your best energy.",
        "Start with one small piece of the big idea.",
        "Your customers' wins are your wins.",
        "Keep learning. Keep earning.",
        "Make your work feel like a welcome.",
        "Every great business was once a small one.",
        "Do it with care, and it shows.",
        "Let curiosity lead the way.",
        "Take a moment to notice what's working.",
        "A thoughtful reply can make someone's day.",
        "Be proud of the progress nobody sees.",
        "Keep showing up. It adds up.",
        "Make it beautiful, even when it's simple.",
        "Trust grows when you keep your word.",
        "A little extra effort goes a long way.",
        "Enjoy the work. It shows in the results.",
        "Finish July with a smile.",
    ),
    8: (
        "A new month full of good chances.",
        "Be the business people recommend.",
        "Every small step is still a step.",
        "The work you love is worth protecting.",
        "Make someone feel welcome today.",
        "Good things take care and time.",
        "You already have enough to begin.",
        "A positive outlook is a business asset.",
        "Do the important thing first.",
        "Let your work speak with kindness.",
        "Ideas grow when you share them.",
        "Every skill you have began with a clumsy first try.",
        "Every day you get a little better at this.",
        "Make your customers' lives easier.",
        "Halfway through August, still moving forward.",
        "Choose one thing and do it wonderfully.",
        "Your consistency is someone's reassurance.",
        "Keep your promises small and your delivery big.",
        "Great service is remembered.",
        "Every day brings a new opportunity to help.",
        "Be thankful for the people who trust you.",
        "Simplicity is a kind of elegance.",
        "Make it count today.",
        "Your best customers are your best teachers.",
        "Steady effort beats bursts of hurry.",
        "Make room for what matters most.",
        "The joy is in the building.",
        "Today, be the reason someone smiles.",
        "Small acts of care build loyal customers.",
        "Look back, smile, and keep going.",
        "Close August with pride.",
    ),
    9: (
        "A new season to learn and grow.",
        "Fresh starts are always available.",
        "Focus on progress, and the results will follow.",
        "Every effort you make is an investment.",
        "Make your work a little more human.",
        "Be clear, be kind, be consistent.",
        "Your persistence is your superpower.",
        "Good questions lead to great answers.",
        "Build something you'd be proud to hand on.",
        "A thank-you note never goes out of style.",
        "Today's patience is tomorrow's payoff.",
        "Make your next step a confident one.",
        "Choose to see the opportunity.",
        "Every customer story is worth listening to.",
        "Midway through September, keep building.",
        "Do the work, and let it speak.",
        "Small daily progress adds up to big change.",
        "Be someone who makes things better.",
        "Keep it simple and keep it going.",
        "A steady hand builds a strong business.",
        "Your energy shapes your day.",
        "Take stock of everything you've grown so far.",
        "Let today's work be your best yet.",
        "Make it easy for people to love what you do.",
        "Generosity is good business.",
        "The best results come from caring about the details.",
        "Keep moving, even if it's slowly.",
        "A kind word is never wasted.",
        "Trust your experience. It's real.",
        "End September knowing you grew.",
    ),
    10: (
        "A new month, a clean slate, a bright start.",
        "Every day is a chance to do good work.",
        "Make your progress visible to yourself.",
        "Good things happen to people who keep going.",
        "Be the business you'd want to find.",
        "Make today a little lighter and a lot better.",
        "Your effort matters more than you know.",
        "Choose focus over busy.",
        "Start with what you can do right now.",
        "Every relationship is built on small moments.",
        "Keep learning. It keeps you ahead.",
        "Make your customers feel like the only ones.",
        "Small steps lead to big places.",
        "Do it with heart.",
        "Halfway through October, still growing.",
        "Your best ideas come from listening.",
        "Be patient. Good things grow slowly.",
        "Make one thing simpler today.",
        "Every finish is a new starting point.",
        "Give yourself credit for showing up.",
        "Make it warm, make it welcoming.",
        "Keep an easy pace. You're in this for the long run.",
        "Do one thing today that moves you forward.",
        "Kindness is always in season.",
        "Trust the work you've put in.",
        "Be the bright spot in someone's day.",
        "Every good business is built by good habits.",
        "Keep going. You're doing better than you think.",
        "Make your work worth talking about.",
        "Notice what's already good. There's more of it than you think.",
        "Close October with something to celebrate.",
    ),
    11: (
        "A new month to be grateful and grow.",
        "Thankfulness makes every day brighter.",
        "Make today about the people you serve.",
        "Your work makes a difference.",
        "Every customer is a relationship worth caring for.",
        "Do a little more than expected.",
        "Make progress, not excuses.",
        "A grateful heart is a strong foundation.",
        "Be proud of what you've built so far.",
        "Keep things simple and kind.",
        "Show appreciation. It's always welcome.",
        "Your consistency builds trust.",
        "One good deed can start a great week.",
        "Let your work reflect your values.",
        "Halfway through November, still giving your best.",
        "Time spent getting better at your craft always pays back.",
        "Small acts of service go a long way.",
        "Keep the faith in what you're building.",
        "Make every interaction count.",
        "Gratitude is good for business.",
        "Every day is a chance to begin again.",
        "Celebrate the people who help you grow.",
        "Be generous with your time and attention.",
        "Count your wins. There are more than you think.",
        "Make today a day of good work.",
        "Thank someone who believed in you.",
        "Share what you've learned.",
        "Rest well. You've earned it.",
        "Let gratitude guide your next step.",
        "End November with a thankful heart.",
    ),
    12: (
        "The last month. Make it a good one.",
        "Finish the year strong and kind.",
        "Every small win this year deserves a nod.",
        "Make someone's season brighter.",
        "Your effort this year built something real.",
        "Give the gift of great service.",
        "Make room for joy in the work.",
        "Reflect, smile, and keep going.",
        "A little kindness makes a big season.",
        "Wrap up what matters, let go of what doesn't.",
        "Every year is built one day at a time.",
        "Share the warmth.",
        "Thank the people who made this year possible.",
        "Do today's work with care.",
        "Halfway through December. Keep shining.",
        "Look how much you've grown this year.",
        "Make your customers' holidays easier.",
        "Every ending makes room for a beginning.",
        "Celebrate the progress you made.",
        "Give yourself the gift of rest.",
        "Keep a little light on for next year's plans.",
        "Gratitude is the best way to close a year.",
        "Your work mattered this year.",
        "Enjoy the people around you.",
        "Peace, joy, and a little rest.",
        "Take a breath. You've done well.",
        "Look back with pride, forward with hope.",
        "Dream a little bigger for next year.",
        "Plan with optimism.",
        "Finish what you can. Forgive what you can't.",
        "A great year ends. A greater one begins.",
    ),
}


def quote_for(day: date) -> str:
    """The quote for `day`'s calendar date."""
    return QUOTES[day.month][day.day - 1]
